"""
Day 9: Define Agent State
Understanding the data structure that flows through our agent.
"""

from typing import TypedDict, List, Optional, Dict, Any
from datetime import datetime
import json

print("=" * 60)
print("📊 DAY 9: DEFINING AGENT STATE")
print("=" * 60)

# ============================================
# Part 1: What is Agent State?
# ============================================
print("\n📚 WHAT IS AGENT STATE?")
print("-" * 40)
print("""
Agent State is the DATA that flows through our agent.

Think of it like a backpack that the agent carries:
- It starts with the question
- As the agent works, it adds more items
- At the end, it has the complete answer

State ensures:
1. All nodes have access to the same data
2. Data persists between steps
3. We can track what happened
4. We can debug the process
""")

# ============================================
# Part 2: Define the AgentState
# ============================================
print("\n📦 PART 2: DEFINING AGENTSTATE")
print("-" * 40)

class AgentState(TypedDict):
    """
    The complete state of our agentic RAG system.
    This flows through all nodes in the LangGraph.
    """
    
    # === INPUT ===
    question: str
    """The original question from the user"""
    
    # === PLANNING ===
    sub_questions: List[str]
    """Sub-questions generated by the planner node"""
    
    # === RETRIEVAL ===
    retrieved_docs: List[str]
    """Document chunks retrieved from the vector store"""
    
    # === GENERATION ===
    draft_answer: str
    """The current draft answer (may be updated)"""
    
    # === EVALUATION ===
    judge_score: float
    """Quality score from 0-10 (0=worst, 10=best)"""
    
    judge_feedback: str
    """Feedback from the judge about what's wrong"""
    
    judge_issue: str
    """Type of issue: hallucination/contradiction/irrelevant/none"""
    
    # === CORRECTION ===
    correction_attempts: int
    """Number of correction attempts made (max 2)"""
    
    correction_history: List[Dict[str, Any]]
    """History of corrections with timestamps"""
    
    # === FINAL ===
    final_answer: str
    """The final answer after all corrections"""
    
    # === METADATA ===
    sources: List[str]
    """Source titles for the final answer"""
    
    start_time: str
    """When the agent started processing"""
    
    node_history: List[str]
    """Track which nodes have been visited"""

print("""
✅ AgentState defined with 13 fields:

INPUT:
    - question: The user's question

PLANNING:
    - sub_questions: Broken down sub-questions

RETRIEVAL:
    - retrieved_docs: Retrieved document chunks

GENERATION:
    - draft_answer: Current answer draft

EVALUATION:
    - judge_score: Quality score (0-10)
    - judge_feedback: What's wrong
    - judge_issue: Type of issue

CORRECTION:
    - correction_attempts: How many fixes tried
    - correction_history: What was fixed

FINAL:
    - final_answer: The final answer
    - sources: Where it came from

METADATA:
    - start_time: When processing started
    - node_history: Which nodes were visited
""")

# ============================================
# Part 3: Create Initial State
# ============================================
print("\n🔄 PART 3: CREATING INITIAL STATE")
print("-" * 40)

def create_initial_state(question: str) -> AgentState:
    """
    Create a fresh state for a new question.
    
    Args:
        question: The user's question
        
    Returns:
        A new AgentState with default values
    """
    return AgentState(
        # Input
        question=question,
        
        # Planning (empty initially)
        sub_questions=[],
        
        # Retrieval (empty initially)
        retrieved_docs=[],
        
        # Generation (empty initially)
        draft_answer="",
        
        # Evaluation (default values)
        judge_score=0.0,
        judge_feedback="",
        judge_issue="none",
        
        # Correction (start at 0)
        correction_attempts=0,
        correction_history=[],
        
        # Final (empty initially)
        final_answer="",
        sources=[],
        
        # Metadata
        start_time=datetime.now().isoformat(),
        node_history=[]
    )

print("✅ create_initial_state() function defined!")

# ============================================
# Part 4: Create Helper Functions
# ============================================
print("\n🔧 PART 4: HELPER FUNCTIONS")
print("-" * 40)

def update_state(state: AgentState, updates: Dict[str, Any]) -> AgentState:
    """
    Safely update state with new values.
    
    Args:
        state: Current state
        updates: Dictionary of fields to update
        
    Returns:
        Updated state
    """
    new_state = dict(state)  # Copy
    new_state.update(updates)  # Apply updates
    return new_state

def add_to_history(state: AgentState, node_name: str) -> AgentState:
    """
    Record that a node was visited.
    
    Args:
        state: Current state
        node_name: Name of the node being visited
        
    Returns:
        Updated state with node added to history
    """
    history = state.get("node_history", [])
    history.append(node_name)
    return update_state(state, {"node_history": history})

def add_correction_record(
    state: AgentState, 
    feedback: str, 
    attempt: int
) -> AgentState:
    """
    Record a correction attempt.
    
    Args:
        state: Current state
        feedback: What was wrong
        attempt: Attempt number
        
    Returns:
        Updated state with correction record
    """
    history = state.get("correction_history", [])
    history.append({
        "attempt": attempt,
        "feedback": feedback,
        "timestamp": datetime.now().isoformat()
    })
    return update_state(state, {
        "correction_history": history,
        "correction_attempts": attempt
    })

print("✅ Helper functions defined:")
print("   - update_state(): Safely update state")
print("   - add_to_history(): Track node visits")
print("   - add_correction_record(): Track corrections")

# ============================================
# Part 5: Test the State
# ============================================
print("\n🧪 PART 5: TESTING THE STATE")
print("-" * 40)

# Create initial state
test_question = "Which magazine did The Doors appear on the cover of in 1967?"
state = create_initial_state(test_question)

print(f"📌 Initial State:")
print(f"   Question: {state['question']}")
print(f"   Start Time: {state['start_time']}")
print(f"   Sub-questions: {state['sub_questions']}")
print(f"   Retrieved Docs: {len(state['retrieved_docs'])}")
print(f"   Draft Answer: '{state['draft_answer']}'")
print(f"   Judge Score: {state['judge_score']}")
print(f"   Correction Attempts: {state['correction_attempts']}")
print(f"   Final Answer: '{state['final_answer']}'")

# ============================================
# Part 6: Simulate State Flow
# ============================================
print("\n🔄 PART 6: SIMULATING STATE FLOW")
print("-" * 40)

print("\n📌 Step 1: PLANNING")
print("-" * 20)

# Plan: Break down the question
state = add_to_history(state, "plan")
state = update_state(state, {
    "sub_questions": [
        "Find information about The Doors",
        "Find which magazine featured The Doors in 1967"
    ]
})

print(f"   Sub-questions: {state['sub_questions']}")
print(f"   Node History: {state['node_history']}")

print("\n📌 Step 2: RETRIEVAL")
print("-" * 20)

# Retrieve: Get documents
state = add_to_history(state, "retrieve")
state = update_state(state, {
    "retrieved_docs": [
        "The Doors were an American rock band formed in 1965...",
        "Rolling Stone is an American monthly magazine...",
        "In 1967, The Doors appeared on the cover of Rolling Stone...",
        "The Doors released their debut album in 1967..."
    ]
})

print(f"   Retrieved {len(state['retrieved_docs'])} documents")
print(f"   First doc: {state['retrieved_docs'][0][:50]}...")
print(f"   Node History: {state['node_history']}")

print("\n📌 Step 3: GENERATION")
print("-" * 20)

# Generate: Write answer
state = add_to_history(state, "generate")
state = update_state(state, {
    "draft_answer": "The Doors appeared on the cover of Rolling Stone magazine in 1967."
})

print(f"   Draft Answer: {state['draft_answer']}")
print(f"   Node History: {state['node_history']}")

print("\n📌 Step 4: JUDGING")
print("-" * 20)

# Judge: Evaluate answer
state = add_to_history(state, "judge")
state = update_state(state, {
    "judge_score": 8.5,
    "judge_feedback": "Answer is correct and well-supported",
    "judge_issue": "none"
})

print(f"   Judge Score: {state['judge_score']}/10")
print(f"   Judge Feedback: {state['judge_feedback']}")
print(f"   Issue Type: {state['judge_issue']}")

print("\n📌 Step 5: FINALIZE")
print("-" * 20)

# Finalize: Complete the answer
state = add_to_history(state, "finalize")
state = update_state(state, {
    "final_answer": "Rolling Stone",
    "sources": ["The Doors", "Rolling Stone"]
})

print(f"   Final Answer: {state['final_answer']}")
print(f"   Sources: {state['sources']}")
print(f"   Node History: {state['node_history']}")

# ============================================
# Part 7: Show Full State
# ============================================
print("\n📊 PART 7: COMPLETE STATE AFTER PROCESSING")
print("-" * 40)

print("\n📋 Full State Dump:")
print(json.dumps(state, indent=2, default=str))

# ============================================
# Part 8: Understanding State Flow
# ============================================
print("\n🔀 PART 8: UNDERSTANDING STATE FLOW")
print("-" * 40)

print("""
How State Flows Through Our Agent:

┌─────────────────────────────────────────────────────────────────┐
│                      AGENT STATE                               │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │ question: "Which magazine did The Doors appear..."     │   │
│  │ sub_questions: []                                      │   │
│  │ retrieved_docs: []                                     │   │
│  │ draft_answer: ""                                       │   │
│  │ judge_score: 0.0                                       │   │
│  │ correction_attempts: 0                                 │   │
│  │ final_answer: ""                                       │   │
│  └─────────────────────────────────────────────────────────┘   │
│                              ↓                                  │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │              PLAN NODE                                  │   │
│  │  Reads: question                                        │   │
│  │  Writes: sub_questions                                 │   │
│  └─────────────────────────────────────────────────────────┘   │
│                              ↓                                  │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │            RETRIEVE NODE                                │   │
│  │  Reads: sub_questions                                   │   │
│  │  Writes: retrieved_docs                                │   │
│  └─────────────────────────────────────────────────────────┘   │
│                              ↓                                  │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │            GENERATE NODE                                │   │
│  │  Reads: retrieved_docs                                  │   │
│  │  Writes: draft_answer                                  │   │
│  └─────────────────────────────────────────────────────────┘   │
│                              ↓                                  │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │             JUDGE NODE                                  │   │
│  │  Reads: retrieved_docs, draft_answer                   │   │
│  │  Writes: judge_score, judge_feedback, judge_issue      │   │
│  └─────────────────────────────────────────────────────────┘   │
│                              ↓                                  │
│                    ┌─────────┴─────────┐                       │
│                    │                   │                       │
│              Score ≥ 7?          Score < 7?                    │
│                    │                   │                       │
│                    ▼                   ▼                       │
│  ┌─────────────────────────┐  ┌─────────────────────────┐    │
│  │    FINALIZE NODE        │  │    CORRECT NODE         │    │
│  │  Reads: draft_answer   │  │  Reads: judge_feedback  │    │
│  │  Writes: final_answer  │  │  Writes: correction_    │    │
│  │          sources        │  │          attempts       │    │
│  └─────────────────────────┘  └─────────────────────────┘    │
└─────────────────────────────────────────────────────────────────┘
""")

# ============================================
# Part 9: State Validation
# ============================================
print("\n✅ PART 9: STATE VALIDATION")
print("-" * 40)

def validate_state(state: AgentState) -> List[str]:
    """
    Validate that the state has all required fields.
    
    Returns:
        List of missing fields (empty if valid)
    """
    required_fields = [
        "question", "sub_questions", "retrieved_docs",
        "draft_answer", "judge_score", "judge_feedback",
        "judge_issue", "correction_attempts", "correction_history",
        "final_answer", "sources", "start_time", "node_history"
    ]
    
    missing = []
    for field in required_fields:
        if field not in state:
            missing.append(field)
    
    return missing

# Test validation
missing = validate_state(state)
if missing:
    print(f"⚠️ Missing fields: {missing}")
else:
    print("✅ All required fields present!")

print(f"\n📊 State Statistics:")
print(f"   - Total fields: {len(state)}")
print(f"   - Question length: {len(state['question'])} chars")
print(f"   - Sub-questions: {len(state['sub_questions'])}")
print(f"   - Retrieved docs: {len(state['retrieved_docs'])}")
print(f"   - Correction attempts: {state['correction_attempts']}")
print(f"   - Node history: {state['node_history']}")

# ============================================
# Part 10: Summary
# ============================================
print("\n📊 DAY 9 SUMMARY")
print("-" * 40)
print("""
✅ Defined AgentState with 13 fields
✅ Created initial state function
✅ Built helper functions for state management
✅ Simulated state flow through the agent
✅ Tested state validation

🎯 Key Concepts:
   1. State holds ALL data for the agent
   2. Each node reads from and writes to state
   3. State flows sequentially through the agent
   4. We track everything for debugging

📋 State Fields:
   1. question          - User's question
   2. sub_questions     - Planned sub-questions
   3. retrieved_docs    - Retrieved chunks
   4. draft_answer      - Current answer
   5. judge_score       - Quality score (0-10)
   6. judge_feedback    - What's wrong
   7. judge_issue       - Type of issue
   8. correction_attempts - How many fixes
   9. correction_history - What was fixed
   10. final_answer     - Final answer
   11. sources          - Source titles
   12. start_time       - Processing start
   13. node_history     - Nodes visited
""")

print("\n🚀 Ready for Day 10! (Planner Node)")
print("=" * 60)